#!/usr/bin/env python3
"""Validate and summarize the EM-004 battery chemistry and capacity trade."""

from __future__ import annotations

import argparse
import csv
from dataclasses import dataclass
from pathlib import Path

from electrical_load_budget import read_loads, totals


WEIGHTS = {
    "thermal_safety": 0.25,
    "lifecycle": 0.15,
    "mass_volume": 0.20,
    "cold_operation": 0.10,
    "integration": 0.15,
    "power_performance": 0.10,
    "availability_cost": 0.05,
}
NOMINAL_BUS_V = 51.2
REFERENCE_MODULE_WH = 5120
REFERENCE_MODULE_KG = 37
REFERENCE_MODULE_COUNT = 2


@dataclass(frozen=True)
class Option:
    option: str
    thermal_safety: int
    lifecycle: int
    mass_volume: int
    cold_operation: int
    integration: int
    power_performance: int
    availability_cost: int
    disposition: str


def read_options(path: Path) -> list[Option]:
    with path.open(newline="", encoding="utf-8") as stream:
        rows = list(csv.DictReader(stream))
    required = set(Option.__dataclass_fields__)
    if not rows:
        raise ValueError("battery trade is empty")
    if set(rows[0]) != required:
        raise ValueError("battery trade columns do not match the controlled schema")
    options: list[Option] = []
    seen: set[str] = set()
    for line_number, row in enumerate(rows, start=2):
        name = row["option"].strip()
        if not name or name in seen:
            raise ValueError(f"line {line_number}: missing or duplicate option")
        seen.add(name)
        scores = {criterion: int(row[criterion]) for criterion in WEIGHTS}
        if any(score < 1 or score > 5 for score in scores.values()):
            raise ValueError(f"line {line_number}: scores must be from 1 to 5")
        options.append(
            Option(
                option=name,
                disposition=row["disposition"].strip(),
                **scores,
            )
        )
    return options


def weighted_score(option: Option) -> float:
    return sum(getattr(option, criterion) * weight for criterion, weight in WEIGHTS.items())


def capacity_results(load_budget: Path) -> dict[str, float]:
    load_result = totals(read_loads(load_budget))
    design_day = max(load_result["summer_daily_wh"], load_result["winter_daily_wh"])
    reference_nominal_wh = REFERENCE_MODULE_WH * REFERENCE_MODULE_COUNT
    return {
        "design_day_wh": design_day,
        "minimum_nominal_wh": load_result["battery_planning_wh"],
        "minimum_nominal_ah": load_result["battery_planning_wh"] / NOMINAL_BUS_V,
        "reference_nominal_wh": reference_nominal_wh,
        "reference_mass_kg": REFERENCE_MODULE_KG * REFERENCE_MODULE_COUNT,
        "reference_operational_days": reference_nominal_wh * 0.80 / (design_day * 1.10),
        "peak_bus_a": load_result["peak_w"] / NOMINAL_BUS_V,
    }


def markdown(options: list[Option], load_budget: Path) -> str:
    capacity = capacity_results(load_budget)
    ranked = sorted(options, key=weighted_score, reverse=True)
    lines = [
        "# Battery chemistry and capacity trade results",
        "",
        "> Generated by `python3 calculations/battery_trade_study.py`. Do not edit manually.",
        "",
        "## Criteria weights",
        "",
        "| Criterion | Weight |",
        "|---|---:|",
        *[f"| {criterion.replace('_', ' ').title()} | {weight:.0%} |" for criterion, weight in WEIGHTS.items()],
        "",
        "Scores use 1 (least favorable) through 5 (most favorable). Weighting reflects a payload-constrained, "
        "occupied vehicle with a 20-year service objective; it is a decision aid rather than a safety certification.",
        "",
        "## Ranked chemistry result",
        "",
        "| Rank | Chemistry | Weighted score | Disposition |",
        "|---:|---|---:|---|",
    ]
    for rank, option in enumerate(ranked, start=1):
        lines.append(
            f"| {rank} | {option.option} | {weighted_score(option):.2f} / 5 | {option.disposition} |"
        )
    lines.extend(
        [
            "",
            "## Capacity envelope derived from EM-003",
            "",
            "| Result | Value |",
            "|---|---:|",
            f"| Governing daily source energy | {capacity['design_day_wh']:.0f} Wh/day |",
            f"| Minimum nominal planning energy | {capacity['minimum_nominal_wh']:.0f} Wh |",
            f"| Equivalent capacity at {NOMINAL_BUS_V:.1f} V nominal | {capacity['minimum_nominal_ah']:.0f} Ah |",
            f"| Representative two-module LFP envelope | {capacity['reference_nominal_wh']:.0f} Wh |",
            f"| Representative battery-only mass | {capacity['reference_mass_kg']:.0f} kg |",
            f"| Operational days with 80% usable energy and 10% contingency | {capacity['reference_operational_days']:.2f} days |",
            f"| Arithmetic peak current at nominal voltage | {capacity['peak_bus_a']:.1f} A |",
            "",
            "The representative envelope uses two 51.2 V, 100 Ah, 5.12 kWh, 37 kg LFP modules solely to test "
            "packaging and mass. It is not a product selection. Current, protection, low-voltage behavior, module "
            "parallel limits, BMS architecture, thermal control, compliance, and installed mass require separate closure.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, default=Path("calculations/battery-chemistry-trade.csv"))
    parser.add_argument("--load-budget", type=Path, default=Path("calculations/electrical-load-budget.csv"))
    parser.add_argument("--output", type=Path, default=Path("calculations/battery-trade-study-results.md"))
    args = parser.parse_args()
    if abs(sum(WEIGHTS.values()) - 1.0) > 1e-9:
        raise ValueError("criteria weights must sum to 1.0")
    args.output.write_text(markdown(read_options(args.input), args.load_budget), encoding="utf-8")


if __name__ == "__main__":
    main()
