#!/usr/bin/env python3
"""Validate and summarize the SolarChaser preliminary electrical load budget."""

from __future__ import annotations

import argparse
import csv
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable


DOMAIN_EFFICIENCY = {"12V": 0.90, "48V": 0.98, "230V": 0.88}
AUTONOMY_DAYS = 2.0
CONTINGENCY = 0.10
USABLE_FRACTION = 0.80


@dataclass(frozen=True)
class Load:
    load_id: str
    name: str
    domain: str
    criticality: str
    summer_daily_wh: float
    winter_daily_wh: float
    worst_continuous_w: float
    peak_w: float
    certainty: str
    basis: str


def read_loads(path: Path) -> list[Load]:
    with path.open(newline="", encoding="utf-8") as stream:
        rows = list(csv.DictReader(stream))

    required = set(Load.__dataclass_fields__)
    if not rows:
        raise ValueError("load budget is empty")
    if set(rows[0]) != required:
        missing = sorted(required - set(rows[0]))
        extra = sorted(set(rows[0]) - required)
        raise ValueError(f"invalid columns; missing={missing}, extra={extra}")

    loads: list[Load] = []
    seen: set[str] = set()
    for line_number, row in enumerate(rows, start=2):
        load_id = row["load_id"].strip()
        if not load_id or load_id in seen:
            raise ValueError(f"line {line_number}: missing or duplicate load_id {load_id!r}")
        seen.add(load_id)
        domain = row["domain"].strip()
        if domain not in DOMAIN_EFFICIENCY:
            raise ValueError(f"line {line_number}: unsupported domain {domain!r}")
        numbers = {
            key: float(row[key])
            for key in (
                "summer_daily_wh",
                "winter_daily_wh",
                "worst_continuous_w",
                "peak_w",
            )
        }
        if any(value < 0 for value in numbers.values()):
            raise ValueError(f"line {line_number}: load values cannot be negative")
        if numbers["peak_w"] < numbers["worst_continuous_w"]:
            raise ValueError(f"line {line_number}: peak_w is below worst_continuous_w")
        loads.append(
            Load(
                load_id=load_id,
                name=row["name"].strip(),
                domain=domain,
                criticality=row["criticality"].strip(),
                certainty=row["certainty"].strip(),
                basis=row["basis"].strip(),
                **numbers,
            )
        )
    return loads


def source_power(load: Load, field: str) -> float:
    return getattr(load, field) / DOMAIN_EFFICIENCY[load.domain]


def totals(loads: Iterable[Load]) -> dict[str, float]:
    materialized = list(loads)
    result = {
        field: sum(source_power(load, field) for load in materialized)
        for field in (
            "summer_daily_wh",
            "winter_daily_wh",
            "worst_continuous_w",
            "peak_w",
        )
    }
    design_day = max(result["summer_daily_wh"], result["winter_daily_wh"])
    result["battery_planning_wh"] = (
        design_day * AUTONOMY_DAYS * (1 + CONTINGENCY) / USABLE_FRACTION
    )
    return result


def markdown(loads: list[Load]) -> str:
    result = totals(loads)
    lines = [
        "# Preliminary electrical load-budget results",
        "",
        "> Generated by `python3 calculations/electrical_load_budget.py`. Do not edit manually.",
        "",
        "## Conversion assumptions",
        "",
        "| Domain | Planning efficiency |",
        "|---|---:|",
        *[f"| {domain} | {efficiency:.0%} |" for domain, efficiency in DOMAIN_EFFICIENCY.items()],
        "",
        "## Source-side envelope",
        "",
        "| Result | Value |",
        "|---|---:|",
        f"| Summer daily energy | {result['summer_daily_wh']:.0f} Wh/day |",
        f"| Winter daily energy | {result['winter_daily_wh']:.0f} Wh/day |",
        f"| Sum of worst-continuous branch loads | {result['worst_continuous_w']:.0f} W |",
        f"| Arithmetic peak upper bound | {result['peak_w']:.0f} W |",
        f"| Two-day battery planning energy | {result['battery_planning_wh']:.0f} Wh nominal |",
        "",
        "The continuous and peak totals are deliberately conservative arithmetic sums, not a diversity study. "
        "The battery planning value uses the higher seasonal day, two autonomy days, 10% contingency, "
        "and 80% usable energy. It is an input to the battery trade study, not a capacity selection.",
        "",
        "## Load inputs",
        "",
        "| ID | Load | Domain | Summer Wh/day | Winter Wh/day | Continuous W | Peak W | Certainty |",
        "|---|---|---:|---:|---:|---:|---:|---|",
    ]
    for load in loads:
        lines.append(
            f"| {load.load_id} | {load.name} | {load.domain} | "
            f"{load.summer_daily_wh:.0f} | {load.winter_daily_wh:.0f} | "
            f"{load.worst_continuous_w:.0f} | {load.peak_w:.0f} | {load.certainty} |"
        )
    lines.extend(
        [
            "",
            "## Interpretation limits",
            "",
            "- All load values are engineering estimates until measured against selected equipment and use profiles.",
            "- Space heating, water heating, air conditioning, fixed electric cooking, and vehicle traction are excluded.",
            "- The 230 V peak is an operating envelope, not permission to use all possible appliances concurrently.",
            "- Converter and inverter nameplates require transient, temperature, protection, cable, and diversity analysis.",
            "- Solar-array and charger sizing require seasonal generation and mission-profile analyses.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--input",
        type=Path,
        default=Path("calculations/electrical-load-budget.csv"),
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("calculations/electrical-load-budget-results.md"),
    )
    args = parser.parse_args()
    loads = read_loads(args.input)
    args.output.write_text(markdown(loads), encoding="utf-8")


if __name__ == "__main__":
    main()
